/* This file was autogenerated. Do not edit! */
#ifndef _INCL_MOJOSHADER_VERSION_H_
#define _INCL_MOJOSHADER_VERSION_H_
#define MOJOSHADER_VERSION 986
#define MOJOSHADER_CHANGESET "hg-986:805aa6eb75af"
#endif

